---
name: test

"on":
  push:
    branches:
      - master
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '.github/workflows/test.yml'

env:
  go-version: '1.22'

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - run: go vet .
      - run: go build
      - run: go test -cover ./...
